version: '3'

services:
  server:
    image: acfpatrick/streamly:latest
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:3000'
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: postgres
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres: